### ISSUE TITLE
🛠 - [EPIC] New Mask Development (PoC)

### ISSUE THREAD

**Issue by nsbarsukov** [Tinkoff/maskito#1]
This repository is devoted to development of input’s mask .

## What is input mask ?
Mask is a tool to constrain user input.
It is an expression (defined by developer) that helps to define what type of contact is allowed in a given field on a template.

## Why do need it ? 
[Taiga UI’s team](https://github.com/Tinkoff/taiga-ui#core-team) is going to develop this new library.
New mask is required for many our inputs:

<details>
<summary>See full lists with masked Taiga’s inputs:</summary>

* [x] [InputCard](https://taiga-ui.dev/components/input-card) https://github.com/Tinkoff/maskito/issues/76
* [x] [InputCardGrouped](https://taiga-ui.dev/components/input-card-grouped) https://github.com/Tinkoff/maskito/issues/76
* [X] [InputCount](https://taiga-ui.dev/components/input-count) https://github.com/Tinkoff/maskito/issues/46
* [x] [InputDate](https://taiga-ui.dev/components/input-date) https://github.com/Tinkoff/maskito/issues/54
* [x] [InputDateRange](https://taiga-ui.dev/components/input-date-range) https://github.com/Tinkoff/maskito/issues/75
* [x] [InputDateTime](https://taiga-ui.dev/components/input-date-time) https://github.com/Tinkoff/maskito/issues/86
* [X] [InputNumber](https://taiga-ui.dev/components/input-number) https://github.com/Tinkoff/maskito/issues/46
* [x] [InputPhone](https://taiga-ui.dev/components/input-phone) https://github.com/Tinkoff/maskito/issues/77
* [x] [InputPhoneInternational](https://taiga-ui.dev/components/input-phone-international) https://github.com/Tinkoff/maskito/issues/77
* [X] [InputTime](https://taiga-ui.dev/components/input-time) https://github.com/Tinkoff/maskito/issues/30
* [ ] [InputYear](https://taiga-ui.dev/components/input-year)

</details>

Taiga UI is currently using [text-mask](https://github.com/text-mask/text-mask)-library.
This mask is no longer maintained. It is written in Javascript (no Typescript!).
It uses Angular 4 and published with legacy View Engine.
Also, we have many issues with this mask.

See this issue:
* https://github.com/Tinkoff/taiga-ui/issues/120

## What are the requirements for a new mask?

- [X] Strict Typescript
- [X] Angular 12+. Published with Ivy engine.
- [X] SSR support
- [x] Shadow dom support
- [X] New mask should support `HTMLInputElement` & `HTMLTextAreaElement`
- [X] Our previous mask has many issues with caret position after programming inserting/deleting of characters. We should take the previous issues into consideration and find a flexible way for caret-position’s management.
- [ ] Dont forget about IME composition (`compositionstart` / `compositionend` events )
https://github.com/Tinkoff/maskito/issues/85
- [X] Dont forget about "Delete"-button (Windows OS)
- [ ] Dont forget about Ctrl + Backspace/Delete (delete the word)
https://github.com/Tinkoff/maskito/issues/84
- [X] Browser autofill support
- [X] Drop event support
- [X] Predictive text from mobile keyboard support

## Proposed repository structure
We are going to publish 4 libraries under the same scope `@maskito`.

- [x] `@maskito/core`. It contains zero-deps Typescript-library. This library exports only class `new Mask(…)` and some typescript interfaces. All magic happens in this library.
- [x] `@maskito/angular`. It requires `@maskito/core` and `@angular/*` as peer-dependencies. It exports directive for input/textarea-masking.
- [x] `@maskito/kit`. It contains a lot of ready-made solutions of input-masking. For example, utils to create masks for numbers, phone, time, date and etc.
- [ ] `@maskito/react`. This package is under consideration. If there will be demand on this package, we will consider developing it. It exports hook for functional-component development.

### Public API:
```ts
export interface MaskitoOptions {
    // type MaskExpression = Array<RegExp | string> | RegExp;
    mask: MaskExpression | (() => MaskExpression);
    // more options
}

export declare class Maskito {
    constructor(element: HTMLInputElement | HTMLTextAreaElement, options: MaskitoOptions);
    destroy(): void;
}
```

#### 1. InputPhone
```ts
import { Maskito } from '@maskito/core';

const inputRef: HTMLInputElement = document.querySelector('input.css-selector');

const inputPhone = new Maskito(
    this.inputRef,
    { mask: [ '+', '7', '(', /\d/, /\d/, /\d/, ')', /\d/, /\d/, /\d/, '-', /\d/, /\d/, '-', /\d/, /\d/ ] }
);
```

#### 2. InputNumber
```ts
import { Maskito } from '@maskito/core';

const inputRef: HTMLInputElement = document.querySelector('input.css-selector');

const inputNumber = new Maskito(
    this.inputRef,
    { mask: /^\d+(\.\d*)?$/ }
);
```

#### 3. InputDate
```ts
import {Maskito, MaskitoOptions} from '@maskito/core';

const inputRef: HTMLInputElement = document.querySelector('input.css-selector');

const generateDateMaskExpression = (dateMode: 'DMY' | 'YMD' | 'MDY'): MaskitoOptions['mask'] => {
    switch (dateMode) {
        case 'MDY':
            return []; // Array<RegExp | string>
        case "YMD":
            return /.../; // RegExp
        default:
            return []; // Array<RegExp | string>
    }
}

const inputDate = new Maskito(
    this.inputRef,
    { mask: generateDateMaskExpression('DMY') }
);
```
